// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://onrxwzgoqphpwqybsaim.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ucnh3emdvcXBocHdxeWJzYWltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzNzE0ODYsImV4cCI6MjA2Njk0NzQ4Nn0.Cn1bgieI2ftKhAvs2WYQIuupJY14fyA0wjnYb8M1iWU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});